In [126]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [127]:
data = pd.read_csv(r"C:\Users\ADMIN\Downloads\cardiovascular_risk_dataset.csv")
data

,age,bmi,systolic_bp,diastolic_bp,cholesterol_mg_dl,resting_heart_rate,smoking_status,daily_steps,stress_level,physical_activity_hours_per_week,sleep_hours,family_history_heart_disease,diet_quality_score,alcohol_units_per_week,heart_disease_risk_score,risk_category
0,62,25.0,142,93,247,72,Never,11565,3,5.6,8.2,No,7,0.7,28.1,Medium
1,54,29.7,158,101,254,74,Current,4036,8,0.5,6.7,No,5,4.5,63.0,High
2,46,36.2,170,113,276,80,Current,3043,9,0.4,4.0,No,1,20.8,73.1,High
3,48,30.4,153,98,230,73,Former,5604,5,0.6,8.0,No,4,8.5,39.5,Medium
4,46,25.3,139,87,206,69,Current,7464,1,2.0,6.1,No,5,3.6,29.3,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,19,26.0,121,75,185,84,Never,6724,3,2.9,7.2,No,7,0.0,0.0,Low
5496,18,30.9,128,82,235,75,Never,3661,4,0.0,5.5,No,1,9.6,16.8,Low
5497,63,29.5,142,92,239,69,Never,6643,5,4.1,6.9,No,6,2.4,31.8,Medium
5498,46,27.5,138,91,237,65,Never,3279,3,2.4,5.8,Yes,5,2.3,29.4,Medium
5499,79,29.0,157,102,265,82,Never,3066,5,0.0,7.7,No,5,6.3,50.9,Medium

In [128]:
data.isnull().sum()

age                                 0
bmi                                 0
systolic_bp                         0
diastolic_bp                        0
cholesterol_mg_dl                   0
resting_heart_rate                  0
smoking_status                      0
daily_steps                         0
stress_level                        0
physical_activity_hours_per_week    0
sleep_hours                         0
family_history_heart_disease        0
diet_quality_score                  0
alcohol_units_per_week              0
heart_disease_risk_score            0
risk_category                       0
dtype: int64

In [129]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["smoking_status"]=le.fit_transform(data["smoking_status"])
data["family_history_heart_disease"]=le.fit_transform(data["family_history_heart_disease"])

In [130]:
data

,age,bmi,systolic_bp,diastolic_bp,cholesterol_mg_dl,resting_heart_rate,smoking_status,daily_steps,stress_level,physical_activity_hours_per_week,sleep_hours,family_history_heart_disease,diet_quality_score,alcohol_units_per_week,heart_disease_risk_score,risk_category
0,62,25.0,142,93,247,72,2,11565,3,5.6,8.2,0,7,0.7,28.1,Medium
1,54,29.7,158,101,254,74,0,4036,8,0.5,6.7,0,5,4.5,63.0,High
2,46,36.2,170,113,276,80,0,3043,9,0.4,4.0,0,1,20.8,73.1,High
3,48,30.4,153,98,230,73,1,5604,5,0.6,8.0,0,4,8.5,39.5,Medium
4,46,25.3,139,87,206,69,0,7464,1,2.0,6.1,0,5,3.6,29.3,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5495,19,26.0,121,75,185,84,2,6724,3,2.9,7.2,0,7,0.0,0.0,Low
5496,18,30.9,128,82,235,75,2,3661,4,0.0,5.5,0,1,9.6,16.8,Low
5497,63,29.5,142,92,239,69,2,6643,5,4.1,6.9,0,6,2.4,31.8,Medium
5498,46,27.5,138,91,237,65,2,3279,3,2.4,5.8,1,5,2.3,29.4,Medium
5499,79,29.0,157,102,265,82,2,3066,5,0.0,7.7,0,5,6.3,50.9,Medium

In [131]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   age                               5500 non-null   int64
 1   bmi                               5500 non-null   float64
 2   systolic_bp                       5500 non-null   int64
 3   diastolic_bp                      5500 non-null   int64
 4   cholesterol_mg_dl                 5500 non-null   int64
 5   resting_heart_rate                5500 non-null   int64
 6   smoking_status                    5500 non-null   int64
 7   daily_steps                       5500 non-null   int64
 8   stress_level                      5500 non-null   int64
 9   physical_activity_hours_per_week  5500 non-null   float64
 10  sleep_hours                       5500 non-null   float64
 11  family_history_heart_disease      5500 non-null   int64
 12  diet_quality_score                5500 non-null   int64
 13  alcohol_units_per_week            5500 non-null   float64
 14  heart_disease_risk_score          5500 non-null   float64
 15  risk_category                     5500 non-null   object
dtypes: float64(5), int64(10), object(1)
memory usage: 687.6+ KB

In [132]:
data.columns

Index(['age', 'bmi', 'systolic_bp', 'diastolic_bp', 'cholesterol_mg_dl',
       'resting_heart_rate', 'smoking_status', 'daily_steps', 'stress_level',
       'physical_activity_hours_per_week', 'sleep_hours',
       'family_history_heart_disease', 'diet_quality_score',
       'alcohol_units_per_week', 'heart_disease_risk_score', 'risk_category'],
      dtype='object')

In [133]:
d = data.iloc[5496:5497]
dd = np.array(d)
dd

array([[18, 30.9, 128, 82, 235, 75, 2, 3661, 4, 0.0, 5.5, 0, 1, 9.6,
        16.8, 'Low']], dtype=object)

In [134]:
x = data.drop(columns = ["risk_category","heart_disease_risk_score"] , axis = 1)
y = data["risk_category"]

In [135]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 42,test_size = 0.2)

In [136]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [137]:
lr.score(x_test,y_test)

0.7490909090909091

In [138]:
x_train.columns

Index(['age', 'bmi', 'systolic_bp', 'diastolic_bp', 'cholesterol_mg_dl',
       'resting_heart_rate', 'smoking_status', 'daily_steps', 'stress_level',
       'physical_activity_hours_per_week', 'sleep_hours',
       'family_history_heart_disease', 'diet_quality_score',
       'alcohol_units_per_week'],
      dtype='object')

In [139]:
lr.predict([[18, 30.9, 128, 82, 235, 75, 2, 3661, 4, 0.0, 5.5, 0, 1, 9.6]])

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['Low'], dtype=object)

In [140]:
X = data.drop(columns = ["risk_category","heart_disease_risk_score"] , axis = 1)
Y = data["heart_disease_risk_score"]

In [141]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state = 42,test_size = 0.2)

In [142]:
from sklearn.linear_model import LinearRegression
l = LinearRegression()
l.fit(X_train,Y_train)

LinearRegression()

In [143]:
l.score(X_test,Y_test)

0.9689917876380019

In [144]:
l.predict([[18, 30.9, 128, 82, 235, 75, 2, 3661, 4, 0.0, 5.5, 0, 1, 9.6]])

C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([15.89944058])